import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

import 'package:mandtrans_app/database/InitSQLite.dart';

class Translator {

  // The purpose of this is for testing purposes only
  // Madaya to English translations
  final Map<String, String> _translations = {
    'hello': 'kamusta',
    'goodbye': 'paalam',
    'thank': 'salamat',
    'you': 'kaw',
    'eat': 'mokaan',
    'let\'s': 'kita',
    'what': 'unan',
    'is': 'yang',
    'your': 'pangan',
    'name': 'mo',
    'how': 'pila',
    'old': 'edad',
    'where': 'wayn',
    'did': 'yaga\'uya',
    'live': 'yaga\'uya',
    'came': 'yaga-gikan',
    'from': 'maga\'sikon',
    'are': 'yaga-uno',
    'doing': 'kaw',
    'house': 'bay',
    'today': 'adon',
    'who\'s': 'sino',
    'with': 'kaiban',
    'would': 'gusto',
    'like': 'ng',
    'help': 'tabang',
    'quickly': 'pagdali',
    'give': 'tagai',
    'me': 'ako',
    'glass': 'baso',
    'water': 'tubig',
    'please': 'palihog',
    'cellphone': 'selpon',
    'number': 'number',
    'clean': 'hugasi',
    'face': 'bayho',
    'i\'m': 'yamasakit',
    'sick': 'ako',
    'mad': 'yamadaman',
    'hungry': 'yamagutom',
    'stomach': 'tiyan',
    'aching': 'masakit',
    'pee': 'mag-ihi',
    'feeling': 'gilipong',
    'dizzy': 'ako',
    'food': 'pagkan',
    'tastes': 'way',
    'bad': 'lami',
    'floor': 'bantaw',
    'messy': 'malipa',
    'mean': 'pasabot',
    'know': 'yatigam',
    'think': 'pagtuo',
    'happening': 'yamahitabo',
    'here': 'ngani',
    'bedroom': 'higdaanan',
    'bathroom': 'ligoanan',
    'comfort': 'kasilyasan',
    'room': 'kasilyasan',
    'viand': 'utan',
    'my': 'yang',
    'name': 'kanak',
    'is': 'pangan',
    'from': 'adto',
    'age': 'edad',
    'born': 'yama-otaw',
    'on': 'sangawong',
    'parents': 'ginikanan',
    'leave': 'mopanaw',
    'good': 'kadayaw',
    'talking': 'mapag-storya',
    'to': 'kanmu',
    'hope': 'sikira',
    'see': 'magkita',
    'again': 'isab',
    'available': 'mayo',
    'viands': 'ngani',
    'how': 'tagpila',
    'much': 'ngini',
    'dine': 'kaan',
    'in': 'adi',
    'sink': 'lababo',
    'vegetable': 'gulay',
    'fresh': 'presko',
    'kilo': 'kilo',
    'flue': 'tulingan',
    'marlin': 'tulingan',
    'buy': 'papalita',
    'some': 'sang',
    'chilli': 'katumbaw',
    'want': 'gusto',
    'discount': 'hangyo',
    'let': 'papalita',
    'change': 'kambyo',
    'already': 'ya',
    'been': 'kadto',
    'manay': 'manay',
    'eating': 'kaan',
    'banana': 'saging',
    'cooked': 'luto',
    'isn\'t': 'way',
    'tasty': 'lami',
    'woman': 'bobay',
    'beautiful': 'gwapa',
    'take': 'kuhaa',
    'clothes': 'bado',
    'hanging': 'halayan',
    'there': 'ngadto',
    'going': 'mukadto',
    'again': 'isab',
    'happened': 'yamauno',
    'evening': 'dom',
    'morning': 'adlaw',
    'everyone': 'kamayo',
    'now': 'doon',
    'we': 'mo',
    'are': 'kadto',
    'going': 'kami',
    'how': 'na',
    'all': 'kamo',
    'ask': 'mangutana',
    'question': 'pwedi',
    'place': 'lugar',
    'get': 'makaabot',
    'there': 'ngadto',
    'too': 'malayoay',
    'far': 'ngini',
    'use': 'paggamit',
    'walking': 'mabaktas',
    'distance': 'pasingod',
    'fare': 'pamasahe',
    'come': 'sod',
    'in': 'adi',
    'sit': 'pag-ingkod',
    'down': 'palihog',
    'let\'s': 'bayda',
    'go': 'pagdali',
    'hurry': 'pag-apas-apas',
    'quiet': 'katingon',
    'shut': 'pagkatingon',
    'up': 'hintua',
    'stop': 'yan',
    'worry': 'pagkahawan',
    'forget': 'pagkalingawi',
    'help': 'tabangi',
    'yourself': 'kaugalingon',
    'ahead': 'pag-una',
    'know': 'patigama',
    'after': 'pagkatapos',
    'take': 'dalila',
    'with': 'adto',
    'you': 'kanmo',
    'davao': 'davao',
    'pinaka madayaw': 'best',
    'oriental': 'oriental',
    'state': 'state',
    'university': 'university',
    'one': 'isa',
    'best': 'pinaka',
    'schools': 'skwelahan',
    'mati': 'mati',
    'many': 'isa',
    'students': 'mga',
    'this': 'ngini',
    'the': 'yang',
    'university': 'unibersidad',
    'excel': 'yaga',
    'academically': 'achiever'
  };

  // English to Mandaya translations
  final Map<String, String> _reverseTranslations = {
    'kamusta': 'hello',
    'paalam': 'goodbye',
    'salamat': 'thank you',
    'mokaan': 'lets',
    'da': 'eat',
    'kita': 'lets',
    'unan': 'what',
    'pangan': 'name',
    'mo': 'your',
    'pila': 'how',
    'yang': 'is',
    'edad': 'old',
    'wayn': 'where',
    'kaw': 'you',
    'yaga\'uya': 'live',
    'yaga-gikan': 'came',
    'maga\'sikon': 'from',
    'yaga-uno': 'are',
    'doing': 'doing',
    'bay': 'house',
    'mau': 'is',
    'kumusta': 'how',
    'dakaw': 'are',
    'adon': 'today',
    'sino': 'who\'s',
    'kaiban': 'with',
    'gusto': 'would',
    'ng': 'like',
    'tabang': 'help',
    'pagdali': 'quickly',
    'kaan': 'eat',
    'tagai': 'give',
    'ako': 'me',
    'is': 'glass',
    'aka': 'glass',
    'baso': 'glass',
    'na': 'water',
    'tubig': 'water',
    'palihog': 'please',
    'selpon': 'cellphone',
    'number': 'number',
    'hugasi': 'clean',
    'bayho': 'face',
    'yamasakit': 'i\'m',
    'ako': 'sick',
    'yamadaman': 'i\'m',
    'yamagutom': 'i\'m',
    'tiyan': 'stomach',
    'masakit': 'aching',
    'mag-ihi': 'pee',
    'gilipong': 'feeling',
    'ako': 'dizzy',
    'pagkan': 'food',
    'way': 'tastes',
    'lami': 'bad',
    'bantaw': 'floor',
    'malipa': 'messy',
    'pasabot': 'mean',
    'yatigam': 'know',
    'pagtuo': 'think',
    'pagtanaw': 'think',
    'yamahitabo': 'happening',
    'ngani': 'here',
    'higdaanan': 'bedroom',
    'ligoanan': 'bathroom',
    'kasilyasan': 'comfort',
    'utan': 'viand',
    'kanak': 'my',
    'pangan': 'name',
    'adto': 'from',
    'edad': 'age',
    'yama-otaw': 'born',
    'sangawong': 'on',
    'ginikanan': 'parents',
    'mopanaw': 'leave',
    'kadayaw': 'good',
    'mapag-storya': 'talking',
    'kanmu': 'to',
    'sikira': 'hope',
    'magkita': 'see',
    'isab': 'again',
    'mayo': 'available',
    'ngani': 'viands',
    'tagpila': 'how',
    'ngini': 'much',
    'kaan': 'dine',
    'adi': 'in',
    'lababo': 'sink',
    'gulay': 'vegetable',
    'presko': 'fresh',
    'kilo': 'kilo',
    'tulingan': 'flue',
    'papalita': 'buy',
    'sang': 'some',
    'katumbaw': 'chilli',
    'gusto': 'want',
    'hangyo': 'discount',
    'kambyo': 'change',
    'ya': 'already',
    'kadto': 'been',
    'manay': 'manay',
    'saging': 'banana',
    'luto': 'cooked',
    'bobay': 'woman',
    'gwapa': 'beautiful',
    'kuhaa': 'take',
    'bado': 'clothes',
    'halayan': 'hanging',
    'ngadto': 'there',
    'mukadto': 'going',
    'dom': 'evening',
    'adlaw': 'morning',
    'kamayo': 'everyone',
    'doon': 'now',
    'kami': 'we',
    'dato': 'going',
    'ngawon': 'how',
    'mangutana': 'ask',
    'pwedi': 'question',
    'lugar': 'place',
    'makaabot': 'get',
    'malayoay': 'too',
    'pasingod': 'distance',
    'pamasahe': 'fare',
    'sod': 'come',
    'pag-ingkod': 'sit',
    'bayda': 'let\'s',
    'pag-apas-apas': 'hurry',
    'katingon': 'quiet',
    'pagkatingon': 'shut',
    'hintua': 'stop',
    'pagkahawan': 'worry',
    'pagkalingawi': 'forget',
    'tabangi': 'help',
    'kaugalingon': 'yourself',
    'pag-una': 'ahead',
    'patigama': 'know',
    'pagkatapos': 'after',
    'dalila': 'take',
    'davao': 'davao',
    'oriental': 'oriental',
    'state': 'state',
    'university': 'university',
    'isa': 'one',
    'madayaw': 'the',
     'yang': 'the',
    'pinaka ': 'best',
    'skwelahan': 'schools',
    'mati': 'mati',
    'mga': 'many',
    'unibersidad': 'university',
    'yaga': 'excel',
    'achiever': 'academically'
  };


  Future<String> translateText(String inputText, String sourceLanguage, String targetLanguage) async {
    if (sourceLanguage == 'English' && targetLanguage == 'Mandaya') {
      // Split the input text into words
      List<String> words = inputText.toLowerCase().split(' ');

      // Translate each word
      List<String> translatedWords = words.map((word) {
        return _translations.containsKey(word) ? _translations[word]! : word;
      }).toList();

      // Return the translated text
      return translatedWords.join(' ');
    } else if (sourceLanguage == 'Mandaya' && targetLanguage == 'English') {
      List<String> words = inputText.toLowerCase().split(' ');

      List<String> translatedWords = words.map((word) {
        return _reverseTranslations.containsKey(word) ? _reverseTranslations[word]! : word;
      }).toList();

      return translatedWords.join(' ');
    } else {
      return 'Unsupported translation';
    }


  }
  Future<void> insertTranslationsToFirestore() async {
    try {
      // Insert _translations
      //await FirebaseFirestore.instance.collection('EnglishCollection').doc().set(_translations);

      // Insert _reverseTranslations
      //await FirebaseFirestore.instance.collection('MandayaCollection').doc().set(_reverseTranslations);


      // Store translations in SQLite
      InitSQLite().initializeDatabase();
      await InitSQLite().storeTranslationsInSQLite(_translations);
      await InitSQLite().storeReverseTranslationsInSQLite(_reverseTranslations);

      print('Translations inserted successfully!');
    } catch (error) {
      print('Error inserting translations: $error');
    }
  }
}